// Legal and accounting vocabulary dictionary
// Part 2: Tax, accounting, auditing, and financial terminology

export const TAX_IRC_TERMS: string[] = [
  'IRC Section 61', 'IRC Section 83', 'IRC Section 101', 'IRC Section 102',
  'IRC Section 104', 'IRC Section 105', 'IRC Section 106', 'IRC Section 108',
  'IRC Section 119', 'IRC Section 121', 'IRC Section 125', 'IRC Section 132',
  'IRC Section 152', 'IRC Section 162', 'IRC Section 163', 'IRC Section 164',
  'IRC Section 165', 'IRC Section 166', 'IRC Section 167', 'IRC Section 168',
  'IRC Section 170', 'IRC Section 172', 'IRC Section 179', 'IRC Section 183',
  'IRC Section 195', 'IRC Section 197', 'IRC Section 199A', 'IRC Section 212',
  'IRC Section 213', 'IRC Section 215', 'IRC Section 219', 'IRC Section 243',
  'IRC Section 248', 'IRC Section 263', 'IRC Section 263A', 'IRC Section 267',
  'IRC Section 269', 'IRC Section 280A', 'IRC Section 280E', 'IRC Section 301',
  'IRC Section 302', 'IRC Section 303', 'IRC Section 304', 'IRC Section 305',
  'IRC Section 306', 'IRC Section 311', 'IRC Section 312', 'IRC Section 316',
  'IRC Section 318', 'IRC Section 331', 'IRC Section 332', 'IRC Section 336',
  'IRC Section 338', 'IRC Section 351', 'IRC Section 355', 'IRC Section 357',
  'IRC Section 358', 'IRC Section 361', 'IRC Section 362', 'IRC Section 368',
  'IRC Section 381', 'IRC Section 382', 'IRC Section 385', 'IRC Section 401',
  'IRC Section 403', 'IRC Section 408', 'IRC Section 409A', 'IRC Section 412',
  'IRC Section 421', 'IRC Section 422', 'IRC Section 441', 'IRC Section 446',
  'IRC Section 448', 'IRC Section 453', 'IRC Section 461', 'IRC Section 465',
  'IRC Section 469', 'IRC Section 471', 'IRC Section 475', 'IRC Section 482',
  'IRC Section 501', 'IRC Section 509', 'IRC Section 512', 'IRC Section 514',
  'IRC Section 529', 'IRC Section 531', 'IRC Section 541', 'IRC Section 704',
  'IRC Section 707', 'IRC Section 721', 'IRC Section 731', 'IRC Section 734',
  'IRC Section 736', 'IRC Section 741', 'IRC Section 743', 'IRC Section 751',
  'IRC Section 754', 'IRC Section 1001', 'IRC Section 1012', 'IRC Section 1014',
  'IRC Section 1015', 'IRC Section 1031', 'IRC Section 1033', 'IRC Section 1035',
  'IRC Section 1041', 'IRC Section 1059', 'IRC Section 1060', 'IRC Section 1202',
  'IRC Section 1221', 'IRC Section 1231', 'IRC Section 1244', 'IRC Section 1245',
  'IRC Section 1250', 'IRC Section 1361', 'IRC Section 1362', 'IRC Section 1374',
  'IRC Section 1375', 'IRC Section 2001', 'IRC Section 2010', 'IRC Section 2032',
  'IRC Section 2032A', 'IRC Section 2036', 'IRC Section 2038', 'IRC Section 2040',
  'IRC Section 2042', 'IRC Section 2053', 'IRC Section 2055', 'IRC Section 2056',
  'IRC Section 2503', 'IRC Section 2513', 'IRC Section 2518', 'IRC Section 2523',
  'IRC Section 2601', 'IRC Section 2611', 'IRC Section 2631', 'IRC Section 6662',
  'IRC Section 6694', 'IRC Section 6695', 'IRC Section 7201', 'IRC Section 7206',
  'IRC Section 7701', 'IRC Section 7872',
  'ordinary income', 'capital gains', 'long-term capital gains', 'short-term capital gains',
  'adjusted gross income', 'AGI', 'modified adjusted gross income', 'MAGI',
  'alternative minimum tax', 'AMT', 'net operating loss', 'NOL',
  'carryforward', 'carryback', 'tax basis', 'adjusted basis',
  'fair market value', 'FMV', 'passive activity loss', 'at-risk rules',
  'wash sale', 'constructive receipt', 'economic substance doctrine',
  'step transaction doctrine', 'substance over form', 'sham transaction',
  'transfer pricing', 'arms length', 'FIRPTA', 'FATCA', 'FBAR',
  'qualified business income', 'QBI', 'depreciation recapture',
  'like-kind exchange', 'installment sale', 'tax-free reorganization',
  'S corporation', 'C corporation', 'partnership', 'LLC',
  'sole proprietorship', 'pass-through entity', 'disregarded entity',
  'Schedule K-1', 'Form 1040', 'Form 1065', 'Form 1120', 'Form 1120-S',
  'Form 990', 'Form W-2', 'Form 1099', 'Form W-9', 'Form 941',
  'Form 940', 'Form 709', 'Form 706', 'Form 8832', 'Form 2553',
  'estimated tax', 'quarterly payments', 'safe harbor', 'underpayment penalty',
  'tax credit', 'tax deduction', 'above-the-line deduction', 'below-the-line deduction',
  'itemized deduction', 'standard deduction', 'personal exemption',
  'earned income tax credit', 'EITC', 'child tax credit',
  'foreign tax credit', 'research and development credit', 'R&D credit',
  'opportunity zone', 'qualified opportunity fund', 'bonus depreciation',
  'MACRS', 'straight-line depreciation', 'double declining balance',
  'Section 179 expensing', 'cost segregation', 'tangible property regulations',
  'Circular 230', 'tax opinion', 'tax advice', 'tax return preparer',
  'enrolled agent', 'CPA', 'tax attorney', 'IRS audit',
  'correspondence audit', 'field audit', 'office audit',
  'notice of deficiency', 'ninety-day letter', 'thirty-day letter',
  'statutory notice', 'Tax Court petition', 'innocent spouse',
  'offer in compromise', 'installment agreement', 'currently not collectible',
  'statute of limitations', 'assessment', 'collection',
  'trust fund recovery penalty', 'responsible person',
  'generation-skipping transfer tax', 'GSTT', 'estate tax', 'gift tax',
  'unified credit', 'applicable exclusion amount', 'annual exclusion',
  'marital deduction', 'charitable deduction', 'grantor retained annuity trust',
  'GRAT', 'intentionally defective grantor trust', 'IDGT',
  'qualified personal residence trust', 'QPRT', 'family limited partnership',
  'FLP', 'valuation discount', 'minority discount', 'lack of marketability discount',
];

export const GAAP_IFRS_TERMS: string[] = [
  'ASC 205', 'ASC 210', 'ASC 220', 'ASC 230', 'ASC 250', 'ASC 260',
  'ASC 270', 'ASC 272', 'ASC 274', 'ASC 275', 'ASC 280', 'ASC 310',
  'ASC 320', 'ASC 321', 'ASC 323', 'ASC 326', 'ASC 330', 'ASC 340',
  'ASC 350', 'ASC 360', 'ASC 405', 'ASC 410', 'ASC 420', 'ASC 430',
  'ASC 440', 'ASC 450', 'ASC 460', 'ASC 470', 'ASC 480', 'ASC 505',
  'ASC 606', 'ASC 610', 'ASC 715', 'ASC 718', 'ASC 730', 'ASC 740',
  'ASC 805', 'ASC 808', 'ASC 810', 'ASC 815', 'ASC 820', 'ASC 825',
  'ASC 830', 'ASC 835', 'ASC 840', 'ASC 842', 'ASC 845', 'ASC 848',
  'ASC 855', 'ASC 860',
  'IFRS 1', 'IFRS 2', 'IFRS 3', 'IFRS 4', 'IFRS 5', 'IFRS 7',
  'IFRS 8', 'IFRS 9', 'IFRS 10', 'IFRS 11', 'IFRS 12', 'IFRS 13',
  'IFRS 15', 'IFRS 16', 'IFRS 17',
  'IAS 1', 'IAS 2', 'IAS 7', 'IAS 8', 'IAS 10', 'IAS 12',
  'IAS 16', 'IAS 17', 'IAS 19', 'IAS 20', 'IAS 21', 'IAS 23',
  'IAS 24', 'IAS 26', 'IAS 27', 'IAS 28', 'IAS 32', 'IAS 33',
  'IAS 34', 'IAS 36', 'IAS 37', 'IAS 38', 'IAS 39', 'IAS 40', 'IAS 41',
  'revenue recognition', 'lease accounting', 'operating lease', 'finance lease',
  'right-of-use asset', 'lease liability', 'goodwill', 'goodwill impairment',
  'intangible assets', 'amortization of intangibles', 'business combination',
  'purchase price allocation', 'contingent consideration', 'bargain purchase',
  'consolidation', 'variable interest entity', 'VIE', 'noncontrolling interest',
  'equity method', 'fair value measurement', 'Level 1 inputs', 'Level 2 inputs',
  'Level 3 inputs', 'fair value hierarchy', 'mark-to-market',
  'available-for-sale', 'held-to-maturity', 'trading securities',
  'current expected credit losses', 'CECL', 'allowance for doubtful accounts',
  'hedge accounting', 'cash flow hedge', 'fair value hedge', 'net investment hedge',
  'derivative instrument', 'embedded derivative', 'notional amount',
  'stock-based compensation', 'restricted stock units', 'RSU', 'stock options',
  'performance shares', 'Black-Scholes', 'grant date fair value', 'vesting period',
  'income tax provision', 'deferred tax asset', 'deferred tax liability',
  'valuation allowance', 'uncertain tax position', 'FIN 48',
  'GAAP', 'Generally Accepted Accounting Principles',
  'IFRS', 'International Financial Reporting Standards',
  'FASB', 'Financial Accounting Standards Board',
  'IASB', 'International Accounting Standards Board',
  'Accounting Standards Update', 'ASU', 'Accounting Standards Codification',
  'going concern', 'subsequent events', 'related party transactions',
  'segment reporting', 'earnings per share', 'diluted earnings per share',
  'comprehensive income', 'other comprehensive income', 'OCI',
  'accumulated other comprehensive income', 'AOCI',
  'discontinued operations', 'extraordinary items', 'change in accounting estimate',
  'change in accounting principle', 'error correction', 'restatement',
];

export const AUDITING_TERMS: string[] = [
  'AICPA', 'American Institute of Certified Public Accountants',
  'PCAOB', 'Public Company Accounting Oversight Board',
  'generally accepted auditing standards', 'GAAS',
  'Statements on Auditing Standards', 'SAS',
  'PCAOB Auditing Standards', 'AS 1101', 'AS 1201', 'AS 1215',
  'AS 1220', 'AS 1301', 'AS 1305', 'AS 2101', 'AS 2105',
  'AS 2110', 'AS 2201', 'AS 2301', 'AS 2305', 'AS 2310',
  'AS 2401', 'AS 2405', 'AS 2410', 'AS 2501', 'AS 2502',
  'AS 2601', 'AS 2701', 'AS 2710', 'AS 2805', 'AS 2810',
  'AS 2815', 'AS 2820', 'AS 2901', 'AS 3101', 'AS 3105',
  'material misstatement', 'materiality', 'performance materiality',
  'tolerable misstatement', 'audit risk', 'inherent risk', 'control risk',
  'detection risk', 'risk of material misstatement', 'significant risk',
  'internal controls', 'internal control over financial reporting', 'ICFR',
  'control deficiency', 'significant deficiency', 'material weakness',
  'substantive testing', 'test of controls', 'dual-purpose test',
  'substantive analytical procedures', 'tests of details',
  'confirmation', 'positive confirmation', 'negative confirmation',
  'inquiry', 'observation', 'inspection', 'recalculation', 'reperformance',
  'audit evidence', 'sufficient appropriate audit evidence',
  'professional skepticism', 'professional judgment',
  'audit opinion', 'unmodified opinion', 'unqualified opinion',
  'qualified opinion', 'adverse opinion', 'disclaimer of opinion',
  'emphasis of matter', 'other matter paragraph', 'key audit matter',
  'critical audit matter', 'CAM', 'going concern opinion',
  'scope limitation', 'departure from GAAP',
  'management representation letter', 'engagement letter',
  'audit committee', 'audit committee communication',
  'audit planning', 'audit strategy', 'audit plan',
  'sampling', 'statistical sampling', 'non-statistical sampling',
  'sample size', 'sampling risk', 'non-sampling risk',
  'fraud risk factors', 'fraud triangle', 'management override',
  'journal entry testing', 'related party transactions',
  'subsequent events', 'going concern assessment',
  'group audit', 'component auditor', 'principal auditor',
  'specialists', 'using the work of a specialist',
  'integrated audit', 'attestation engagement', 'review engagement',
  'compilation engagement', 'agreed-upon procedures',
  'SOC 1', 'SOC 2', 'SOC 3', 'service organization controls',
  'Type 1 report', 'Type 2 report', 'SSAE 18', 'AT-C Section 320',
  'peer review', 'quality control', 'SQCS',
];

export const FINANCIAL_TERMS: string[] = [
  'accounts receivable', 'accounts payable', 'accrued expenses',
  'accrued liabilities', 'accrual basis', 'cash basis',
  'modified accrual basis', 'depreciation', 'amortization',
  'EBITDA', 'EBIT', 'net income', 'gross profit', 'gross margin',
  'operating income', 'operating margin', 'net margin',
  'working capital', 'current ratio', 'quick ratio', 'acid test',
  'debt-to-equity ratio', 'leverage ratio', 'interest coverage ratio',
  'return on assets', 'ROA', 'return on equity', 'ROE',
  'return on investment', 'ROI', 'return on capital employed', 'ROCE',
  'retained earnings', 'stockholders equity', 'shareholders equity',
  'treasury stock', 'paid-in capital', 'additional paid-in capital',
  'par value', 'book value', 'carrying value', 'net book value',
  'balance sheet', 'income statement', 'statement of operations',
  'cash flow statement', 'statement of cash flows',
  'statement of stockholders equity', 'statement of comprehensive income',
  'trial balance', 'general ledger', 'subsidiary ledger',
  'journal entry', 'adjusting entry', 'closing entry', 'reversing entry',
  'chart of accounts', 'double-entry bookkeeping',
  'debit', 'credit', 'contra account', 'T-account',
  'bank reconciliation', 'reconciling items', 'outstanding checks',
  'deposits in transit', 'NSF check', 'petty cash',
  'cost of goods sold', 'COGS', 'inventory', 'FIFO', 'LIFO',
  'weighted average cost', 'specific identification',
  'lower of cost or market', 'lower of cost or net realizable value',
  'inventory turnover', 'days sales outstanding', 'DSO',
  'days payable outstanding', 'DPO', 'cash conversion cycle',
  'capital expenditure', 'CapEx', 'operating expenditure', 'OpEx',
  'free cash flow', 'FCF', 'discounted cash flow', 'DCF',
  'net present value', 'NPV', 'internal rate of return', 'IRR',
  'weighted average cost of capital', 'WACC', 'cost of equity',
  'cost of debt', 'capital structure', 'enterprise value',
  'market capitalization', 'price-to-earnings ratio', 'P/E ratio',
  'price-to-book ratio', 'P/B ratio', 'dividend yield',
  'earnings yield', 'PEG ratio', 'enterprise value to EBITDA',
  'asset impairment', 'write-down', 'write-off',
  'provision', 'contingent liability', 'contingent asset',
  'off-balance sheet', 'special purpose entity', 'SPE',
  'intercompany transactions', 'intercompany eliminations',
  'transfer pricing', 'cost allocation', 'activity-based costing',
  'standard costing', 'variance analysis', 'budget variance',
  'favorable variance', 'unfavorable variance',
  'contribution margin', 'breakeven analysis', 'breakeven point',
  'fixed costs', 'variable costs', 'semi-variable costs',
  'direct costs', 'indirect costs', 'overhead',
  'manufacturing overhead', 'applied overhead', 'underapplied overhead',
  'overapplied overhead', 'job order costing', 'process costing',
];
