// Legal and accounting vocabulary dictionary
// Part 1: Legal terminology categories
// These terms are sent to OpenAI Whisper as vocabulary hints
// to improve transcription accuracy for legal professionals.

export const LATIN_LEGAL_PHRASES: string[] = [
  'habeas corpus', 'res judicata', 'stare decisis', 'prima facie', 'pro bono',
  'ad litem', 'amicus curiae', 'bona fide', 'caveat emptor', 'de facto',
  'de jure', 'ex parte', 'in camera', 'inter alia', 'ipso facto',
  'mens rea', 'actus reus', 'nolo contendere', 'per curiam', 'pro se',
  'quantum meruit', 'res ipsa loquitur', 'subpoena duces tecum', 'voir dire',
  'certiorari', 'mandamus', 'quo warranto', 'habeas corpus ad subjiciendum',
  'in personam', 'in rem', 'quasi in rem', 'lis pendens', 'pendente lite',
  'nunc pro tunc', 'sua sponte', 'ab initio', 'ad hoc', 'ad valorem',
  'animus', 'arguendo', 'capias', 'causa mortis', 'compos mentis',
  'corpus delicti', 'cui bono', 'de minimis', 'de novo', 'dictum',
  'duces tecum', 'ejusdem generis', 'en banc', 'et al', 'et seq',
  'et ux', 'ex officio', 'ex post facto', 'fiat', 'fiduciary',
  'functus officio', 'gravamen', 'guardian ad litem', 'habendum',
  'id est', 'in extremis', 'in forma pauperis', 'in futuro', 'in haec verba',
  'in limine', 'in loco parentis', 'in pari delicto', 'in perpetuity',
  'in propria persona', 'in situ', 'in terrorem', 'in toto', 'inter se',
  'inter vivos', 'jus', 'laches', 'lex fori', 'lex loci', 'mala in se',
  'mala prohibita', 'modus operandi', 'nexus', 'nisi',
  'nolle prosequi', 'non sequitur', 'obiter dictum', 'onus probandi',
  'ore tenus', 'pari passu', 'per capita', 'per diem', 'per se',
  'per stirpes', 'post mortem', 'pro forma', 'pro hac vice', 'pro rata',
  'pro tanto', 'pro tempore', 'qua', 'quash', 'quasi',
  'quid pro quo', 'ratio decidendi', 'res gestae', 'res nova',
  'respondeat superior', 'scienter', 'seriatim', 'sine die', 'sine qua non',
  'situs', 'status quo', 'sub judice', 'sub silentio', 'sui generis',
  'supersedeas', 'supra', 'ultra vires', 'vel non', 'venire',
  'vexatious', 'vi et armis', 'videlicet', 'viz', 'volenti non fit injuria',
  'corpus juris', 'jus cogens', 'pacta sunt servanda', 'rebus sic stantibus',
  'erga omnes', 'lex specialis', 'lex posterior', 'lex superior',
  'opinio juris', 'jus ad bellum', 'jus in bello', 'comitas gentium',
  'forum non conveniens', 'renvoi', 'obiter dicta', 'ratio legis',
  'travaux preparatoires', 'jus tertii', 'nemo judex in causa sua',
  'audi alteram partem', 'doli incapax', 'novus actus interveniens',
  'res nullius', 'terra nullius', 'animus possidendi', 'animus contrahendi',
  'consensus ad idem', 'uberrimae fidei', 'contra proferentem',
  'ex turpi causa', 'damnum sine injuria', 'injuria sine damno',
  'ubi jus ibi remedium', 'cessante ratione legis cessat ipsa lex',
];

export const COURT_LITIGATION_TERMS: string[] = [
  'plaintiff', 'defendant', 'appellant', 'appellee', 'respondent',
  'petitioner', 'cross-examination', 'deposition', 'interrogatories',
  'discovery', 'motion to dismiss', 'summary judgment', 'preliminary injunction',
  'temporary restraining order', 'default judgment', 'directed verdict',
  'judgment notwithstanding the verdict', 'remand', 'reversal', 'affirmance',
  'demurrer', 'answer', 'counterclaim', 'cross-claim', 'third-party complaint',
  'interpleader', 'intervention', 'joinder', 'consolidation', 'severance',
  'bifurcation', 'class action', 'class certification', 'opt-out',
  'lead plaintiff', 'named plaintiff', 'putative class', 'class representative',
  'standing', 'justiciability', 'ripeness', 'mootness', 'political question',
  'subject matter jurisdiction', 'personal jurisdiction', 'venue',
  'removal', 'remand to state court', 'diversity jurisdiction',
  'federal question jurisdiction', 'supplemental jurisdiction',
  'pendent jurisdiction', 'abstention', 'preemption',
  'motion for reconsideration', 'motion in limine', 'motion to compel',
  'motion for protective order', 'motion to quash', 'motion for sanctions',
  'motion to strike', 'motion for judgment on the pleadings',
  'motion for new trial', 'motion for relief from judgment',
  'motion to intervene', 'motion to consolidate', 'motion to bifurcate',
  'motion for continuance', 'motion to amend', 'motion to sever',
  'stipulation', 'settlement', 'consent decree', 'plea bargain',
  'plea agreement', 'guilty plea', 'not guilty plea', 'arraignment',
  'preliminary hearing', 'grand jury', 'indictment', 'information',
  'complaint', 'summons', 'service of process', 'proof of service',
  'return of service', 'waiver of service', 'long-arm statute',
  'minimum contacts', 'purposeful availment', 'specific jurisdiction',
  'general jurisdiction', 'forum selection clause', 'choice of law',
  'conflict of laws', 'governing law', 'applicable law',
  'burden of proof', 'preponderance of the evidence', 'clear and convincing evidence',
  'beyond a reasonable doubt', 'probable cause', 'reasonable suspicion',
  'admissibility', 'relevance', 'materiality', 'competence',
  'hearsay', 'hearsay exception', 'excited utterance', 'present sense impression',
  'statement against interest', 'dying declaration', 'business records exception',
  'best evidence rule', 'parol evidence rule', 'authentication',
  'chain of custody', 'expert witness', 'lay witness', 'fact witness',
  'character witness', 'hostile witness', 'impeachment', 'rehabilitation',
  'direct examination', 'redirect examination', 'recross-examination',
  'leading question', 'foundation', 'objection', 'sustained', 'overruled',
  'sidebar', 'bench conference', 'jury instruction', 'jury charge',
  'special verdict', 'general verdict', 'polling the jury',
  'hung jury', 'mistrial', 'acquittal', 'conviction', 'sentencing',
  'restitution', 'probation', 'parole', 'incarceration',
  'appellate brief', 'reply brief', 'amicus brief', 'petition for review',
  'writ of certiorari', 'writ of mandamus', 'writ of prohibition',
  'writ of habeas corpus', 'interlocutory appeal', 'final judgment',
  'collateral order doctrine', 'mandamus review', 'plain error',
  'harmless error', 'reversible error', 'abuse of discretion',
  'de novo review', 'clearly erroneous', 'substantial evidence',
  'arbitrary and capricious', 'rational basis', 'strict scrutiny',
  'intermediate scrutiny', 'compelling interest', 'narrowly tailored',
  'overbreadth', 'vagueness', 'due process', 'equal protection',
  'privileges and immunities', 'full faith and credit', 'comity',
  'estoppel', 'collateral estoppel', 'issue preclusion', 'claim preclusion',
  'law of the case', 'judicial notice', 'presumption', 'inference',
  'circumstantial evidence', 'direct evidence', 'demonstrative evidence',
  'documentary evidence', 'testimonial evidence', 'physical evidence',
  'spoliation', 'adverse inference', 'sanctions', 'contempt of court',
  'civil contempt', 'criminal contempt', 'subpoena', 'subpoena ad testificandum',
  'writ of execution', 'garnishment', 'attachment', 'levy',
  'judgment lien', 'judgment debtor', 'judgment creditor',
  'satisfaction of judgment', 'abstract of judgment', 'domestication of judgment',
  'declaratory judgment', 'injunctive relief', 'equitable relief',
  'specific performance', 'rescission', 'reformation', 'replevin',
  'mandamus relief', 'prohibition relief', 'quo warranto relief',
  'treble damages', 'punitive damages', 'compensatory damages',
  'nominal damages', 'consequential damages', 'incidental damages',
  'general damages', 'special damages', 'liquidated damages',
  'unliquidated damages', 'mitigation of damages', 'proximate cause',
  'cause in fact', 'but-for causation', 'substantial factor test',
  'foreseeability', 'duty of care', 'breach of duty', 'negligence per se',
  'contributory negligence', 'comparative negligence', 'assumption of risk',
  'joint and several liability', 'vicarious liability', 'strict liability',
  'product liability', 'premises liability', 'professional malpractice',
  'legal malpractice', 'medical malpractice', 'wrongful death',
  'survival action', 'loss of consortium', 'emotional distress',
  'intentional infliction of emotional distress', 'negligent infliction of emotional distress',
  'defamation', 'libel', 'slander', 'slander per se',
  'invasion of privacy', 'false light', 'misappropriation',
  'intrusion upon seclusion', 'public disclosure of private facts',
  'tortious interference', 'conversion', 'trespass', 'nuisance',
  'fraud', 'constructive fraud', 'fraudulent misrepresentation',
  'negligent misrepresentation', 'unjust enrichment', 'quantum valebant',
];

export const CONTRACT_LAW_TERMS: string[] = [
  'indemnification', 'force majeure', 'liquidated damages', 'severability',
  'consideration', 'mutual assent', 'offer', 'acceptance', 'counteroffer',
  'revocation', 'rejection', 'mailbox rule', 'mirror image rule',
  'battle of the forms', 'integration clause', 'merger clause',
  'entire agreement clause', 'parol evidence', 'course of dealing',
  'course of performance', 'usage of trade', 'implied covenant of good faith',
  'duty of good faith and fair dealing', 'anticipatory repudiation',
  'anticipatory breach', 'material breach', 'minor breach', 'total breach',
  'partial breach', 'fundamental breach', 'cure', 'adequate assurances',
  'mitigation', 'cover', 'expectation damages', 'reliance damages',
  'restitution damages', 'specific performance', 'injunctive relief',
  'rescission', 'reformation', 'novation', 'accord and satisfaction',
  'modification', 'waiver', 'estoppel', 'promissory estoppel',
  'equitable estoppel', 'detrimental reliance', 'statute of frauds',
  'writing requirement', 'part performance', 'unconscionability',
  'procedural unconscionability', 'substantive unconscionability',
  'adhesion contract', 'boilerplate', 'standard form contract',
  'conditions precedent', 'conditions subsequent', 'concurrent conditions',
  'express condition', 'implied condition', 'constructive condition',
  'condition of satisfaction', 'assignment', 'delegation', 'third-party beneficiary',
  'intended beneficiary', 'incidental beneficiary', 'creditor beneficiary',
  'donee beneficiary', 'privity of contract', 'warranty', 'express warranty',
  'implied warranty', 'implied warranty of merchantability',
  'implied warranty of fitness for a particular purpose', 'warranty of title',
  'disclaimer', 'limitation of liability', 'cap on liability',
  'consequential damages waiver', 'exclusive remedy', 'indemnity',
  'hold harmless', 'contribution', 'subrogation', 'exculpatory clause',
  'non-compete clause', 'non-solicitation clause', 'non-disclosure agreement',
  'confidentiality agreement', 'trade secret', 'proprietary information',
  'intellectual property assignment', 'work for hire', 'license',
  'sublicense', 'royalty', 'termination', 'termination for cause',
  'termination for convenience', 'expiration', 'renewal', 'automatic renewal',
  'notice provision', 'cure period', 'grace period', 'representations and warranties',
  'covenants', 'closing conditions', 'material adverse change',
  'material adverse effect', 'bring-down condition', 'survival clause',
  'choice of law clause', 'forum selection clause', 'arbitration clause',
  'mediation clause', 'dispute resolution', 'escalation clause',
  'most favored nation clause', 'right of first refusal', 'right of first offer',
  'option agreement', 'put option', 'call option', 'earnout',
  'clawback', 'escrow', 'holdback', 'true-up', 'working capital adjustment',
  'purchase price adjustment', 'closing', 'pre-closing covenant',
  'post-closing covenant', 'non-competition period', 'restricted territory',
  'permitted transferee', 'change of control', 'anti-assignment clause',
  'successors and assigns', 'counterparts', 'electronic signatures',
  'recitals', 'whereas clauses', 'definitions section', 'schedules',
  'exhibits', 'attachments', 'amendments', 'addenda', 'side letter',
];

export const CORPORATE_LAW_TERMS: string[] = [
  'articles of incorporation', 'bylaws', 'fiduciary duty', 'duty of care',
  'duty of loyalty', 'duty of good faith', 'business judgment rule',
  'corporate veil', 'piercing the corporate veil', 'alter ego doctrine',
  'board of directors', 'shareholder', 'stockholder', 'officer',
  'chief executive officer', 'chief financial officer', 'chief operating officer',
  'general counsel', 'corporate secretary', 'registered agent',
  'registered office', 'principal place of business', 'state of incorporation',
  'certificate of incorporation', 'certificate of formation',
  'articles of organization', 'operating agreement', 'partnership agreement',
  'limited partnership', 'general partnership', 'limited liability company',
  'limited liability partnership', 'professional corporation',
  'S corporation', 'C corporation', 'B corporation', 'benefit corporation',
  'close corporation', 'closely held corporation', 'publicly traded company',
  'initial public offering', 'secondary offering', 'private placement',
  'Regulation D', 'Rule 506', 'accredited investor', 'qualified institutional buyer',
  'Securities Act of 1933', 'Securities Exchange Act of 1934',
  'Sarbanes-Oxley Act', 'Dodd-Frank Act', 'proxy statement',
  'proxy solicitation', 'annual meeting', 'special meeting',
  'written consent', 'quorum', 'majority vote', 'supermajority',
  'plurality vote', 'cumulative voting', 'straight voting',
  'authorized shares', 'issued shares', 'outstanding shares', 'treasury stock',
  'common stock', 'preferred stock', 'convertible preferred stock',
  'participating preferred', 'liquidation preference', 'dividend',
  'distribution', 'stock split', 'reverse stock split', 'stock buyback',
  'share repurchase', 'preemptive rights', 'anti-dilution protection',
  'weighted average anti-dilution', 'full ratchet anti-dilution',
  'pay-to-play provision', 'drag-along rights', 'tag-along rights',
  'co-sale rights', 'registration rights', 'demand registration',
  'piggyback registration', 'S-3 registration', 'lock-up period',
  'insider trading', 'material nonpublic information', 'Rule 10b-5',
  'Section 16', 'short-swing profits', 'beneficial ownership',
  'Schedule 13D', 'Schedule 13G', 'Form 4', 'Form 8-K', 'Form 10-K',
  'Form 10-Q', 'merger', 'acquisition', 'consolidation', 'tender offer',
  'asset purchase', 'stock purchase', 'reverse merger', 'triangular merger',
  'forward triangular merger', 'reverse triangular merger',
  'statutory merger', 'short-form merger', 'squeeze-out merger',
  'appraisal rights', 'dissenters rights', 'fairness opinion',
  'due diligence', 'letter of intent', 'memorandum of understanding',
  'term sheet', 'definitive agreement', 'purchase agreement',
  'merger agreement', 'asset purchase agreement', 'stock purchase agreement',
  'shareholders agreement', 'voting agreement', 'voting trust',
  'irrevocable proxy', 'standstill agreement', 'no-shop clause',
  'go-shop clause', 'fiduciary out', 'break-up fee', 'reverse break-up fee',
  'hell-or-high-water clause', 'material adverse change clause',
  'Hart-Scott-Rodino Act', 'antitrust clearance', 'regulatory approval',
  'corporate governance', 'board committee', 'audit committee',
  'compensation committee', 'nominating committee', 'independent director',
  'lead independent director', 'executive compensation',
  'stock option plan', 'restricted stock unit', 'employee stock ownership plan',
  'golden parachute', 'golden handcuffs', 'clawback provision',
  'say-on-pay', 'shareholder proposal', 'shareholder derivative action',
  'direct action', 'books and records inspection', 'Section 220 demand',
  'dissolution', 'winding up', 'liquidation', 'receivership',
  'bankruptcy', 'Chapter 7', 'Chapter 11', 'Chapter 13',
  'debtor in possession', 'automatic stay', 'proof of claim',
  'plan of reorganization', 'confirmation', 'discharge',
  'fraudulent transfer', 'preferential transfer', 'avoidance action',
];

export const CRIMINAL_LAW_TERMS: string[] = [
  'felony', 'misdemeanor', 'arraignment', 'bail', 'indictment',
  'information', 'grand jury', 'preliminary hearing', 'probable cause',
  'reasonable suspicion', 'search warrant', 'arrest warrant', 'bench warrant',
  'Miranda rights', 'Miranda warning', 'right to counsel',
  'right to remain silent', 'self-incrimination', 'Fifth Amendment',
  'Sixth Amendment', 'Fourth Amendment', 'Eighth Amendment',
  'due process', 'equal protection', 'double jeopardy',
  'speedy trial', 'public trial', 'jury trial', 'bench trial',
  'prosecution', 'prosecutor', 'district attorney', 'state attorney',
  'United States Attorney', 'Attorney General', 'public defender',
  'defense attorney', 'defense counsel', 'appointed counsel',
  'plea bargain', 'plea agreement', 'plea deal', 'guilty plea',
  'not guilty plea', 'no contest', 'Alford plea',
  'charge bargaining', 'sentence bargaining', 'cooperation agreement',
  'proffer agreement', 'immunity', 'transactional immunity',
  'use immunity', 'derivative use immunity', 'compelled testimony',
  'homicide', 'murder', 'first-degree murder', 'second-degree murder',
  'voluntary manslaughter', 'involuntary manslaughter', 'vehicular homicide',
  'felony murder', 'capital murder', 'aggravated assault', 'simple assault',
  'battery', 'aggravated battery', 'robbery', 'armed robbery',
  'burglary', 'breaking and entering', 'larceny', 'grand larceny',
  'petit larceny', 'theft', 'shoplifting', 'embezzlement',
  'fraud', 'wire fraud', 'mail fraud', 'bank fraud',
  'securities fraud', 'tax fraud', 'insurance fraud', 'identity theft',
  'forgery', 'counterfeiting', 'money laundering', 'racketeering',
  'RICO', 'conspiracy', 'solicitation', 'attempt',
  'aiding and abetting', 'accessory before the fact', 'accessory after the fact',
  'principal', 'accomplice', 'co-conspirator', 'unindicted co-conspirator',
  'arson', 'kidnapping', 'false imprisonment', 'extortion',
  'blackmail', 'bribery', 'perjury', 'obstruction of justice',
  'tampering with evidence', 'witness tampering', 'contempt of court',
  'resisting arrest', 'evading arrest', 'disorderly conduct',
  'trespass', 'vandalism', 'criminal mischief', 'stalking',
  'harassment', 'domestic violence', 'protective order', 'restraining order',
  'drug possession', 'drug trafficking', 'drug distribution',
  'controlled substance', 'Schedule I', 'Schedule II',
  'driving under the influence', 'driving while intoxicated',
  'sentencing', 'mandatory minimum', 'sentencing guidelines',
  'presentence report', 'restitution', 'fine', 'probation',
  'supervised release', 'parole', 'incarceration', 'imprisonment',
  'life sentence', 'death penalty', 'capital punishment',
  'commutation', 'pardon', 'clemency', 'expungement', 'sealing of records',
  'juvenile delinquency', 'juvenile court', 'adjudication',
  'disposition', 'diversion', 'deferred prosecution',
  'pretrial diversion', 'drug court', 'mental health court',
  'habitual offender', 'three strikes law', 'recidivism',
  'sex offender registry', 'Megans Law', 'community notification',
];

export const PROPERTY_REAL_ESTATE_TERMS: string[] = [
  'easement', 'encumbrance', 'lien', 'mortgage', 'deed of trust',
  'promissory note', 'foreclosure', 'judicial foreclosure',
  'non-judicial foreclosure', 'deficiency judgment', 'short sale',
  'deed in lieu of foreclosure', 'loan modification', 'forbearance',
  'title', 'clear title', 'marketable title', 'insurable title',
  'cloud on title', 'quiet title action', 'title search', 'title insurance',
  'title commitment', 'title opinion', 'abstract of title',
  'chain of title', 'recording', 'recording act', 'race statute',
  'notice statute', 'race-notice statute', 'bona fide purchaser',
  'constructive notice', 'actual notice', 'inquiry notice',
  'deed', 'warranty deed', 'general warranty deed', 'special warranty deed',
  'quitclaim deed', 'grant deed', 'bargain and sale deed',
  'deed of gift', 'correction deed', 'deed restriction',
  'restrictive covenant', 'covenant running with the land',
  'equitable servitude', 'real covenant', 'homeowners association',
  'declaration of covenants conditions and restrictions',
  'fee simple absolute', 'fee simple defeasible', 'fee simple determinable',
  'fee simple subject to condition subsequent', 'fee simple subject to executory limitation',
  'life estate', 'remainder', 'vested remainder', 'contingent remainder',
  'executory interest', 'shifting executory interest', 'springing executory interest',
  'reversion', 'possibility of reverter', 'right of entry',
  'rule against perpetuities', 'tenancy in common', 'joint tenancy',
  'right of survivorship', 'tenancy by the entirety', 'community property',
  'partition', 'partition by sale', 'partition in kind',
  'adverse possession', 'tacking', 'color of title', 'prescriptive easement',
  'easement by necessity', 'easement by implication', 'easement appurtenant',
  'easement in gross', 'dominant estate', 'servient estate',
  'license', 'profit a prendre', 'covenant of quiet enjoyment',
  'covenant of seisin', 'covenant of right to convey',
  'covenant against encumbrances', 'covenant of warranty',
  'covenant of further assurances', 'fixture', 'trade fixture',
  'appurtenance', 'riparian rights', 'littoral rights',
  'water rights', 'mineral rights', 'subsurface rights', 'air rights',
  'eminent domain', 'condemnation', 'just compensation', 'inverse condemnation',
  'regulatory taking', 'zoning', 'variance', 'special use permit',
  'conditional use permit', 'nonconforming use', 'spot zoning',
  'subdivision', 'plat', 'survey', 'metes and bounds',
  'lot and block', 'government survey system', 'section', 'township', 'range',
  'appraisal', 'fair market value', 'assessed value', 'appraised value',
  'comparable sales', 'highest and best use', 'property tax',
  'tax assessment', 'tax lien', 'tax sale', 'redemption period',
  'homestead exemption', 'purchase agreement', 'earnest money',
  'option to purchase', 'right of first refusal',
  'closing', 'settlement', 'escrow', 'closing costs', 'title charges',
  'real estate transfer tax', 'recording fees', 'survey fee',
  'home inspection', 'environmental assessment', 'Phase I environmental',
  'Phase II environmental', 'hazardous materials', 'asbestos',
  'lead-based paint', 'radon', 'mold remediation', 'wetlands',
  'flood zone', 'FEMA flood map', 'flood insurance',
  'landlord', 'tenant', 'lease', 'commercial lease', 'residential lease',
  'ground lease', 'sublease', 'assignment of lease', 'lease termination',
  'eviction', 'unlawful detainer', 'constructive eviction', 'actual eviction',
  'security deposit', 'rent escalation', 'triple net lease',
  'gross lease', 'modified gross lease', 'percentage lease',
  'common area maintenance', 'tenant improvements', 'build-out',
  'leasehold interest', 'leasehold improvements', 'surrender of lease',
];
